"""empty message

Revision ID: 20de40b7ae05
Revises: 3c71a35f3fb7
Create Date: 2021-03-22 16:04:29.023391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20de40b7ae05'
down_revision = '3c71a35f3fb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    op.drop_column('Artist', 'seeking_Venue')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_Venue', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('Artist', 'seeking_venue')
    # ### end Alembic commands ###
